name: Docker Image CI

on:
  push:
    branches: [ master ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Push Docker Image
      uses: docker/build-push-action@v1.1.1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: ${{ GITHUB_ENV.GITHUB_REPOSITORY }}
        tags: latest
        push: true
        
        
